"""initial_schema

Revision ID: 46a820fcb3c2
Revises: 
Create Date: 2026-04-24 16:54:56.475821+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a820fcb3c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_participants', sa.Column('claim_receipt_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_campaign_participants_campaign_id'), 'campaign_participants', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_participants_user_id'), 'campaign_participants', ['user_id'], unique=False)
    op.create_unique_constraint('uq_participant_campaign_user', 'campaign_participants', ['campaign_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_participant_campaign_user', 'campaign_participants', type_='unique')
    op.drop_index(op.f('ix_campaign_participants_user_id'), table_name='campaign_participants')
    op.drop_index(op.f('ix_campaign_participants_campaign_id'), table_name='campaign_participants')
    op.drop_column('campaign_participants', 'claim_receipt_id')
    # ### end Alembic commands ###
